domain_path: D:\UTCN\AN_3\Semestru1\SSC\Proiect\platforma_semafor\export\platforma_semafor\sw\standalone_ps7_cortexa9_0
app_src_dir: D:\Vivado\Vitis\2024.2\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
lang: c
